package com.jinanlongen.flume.interceptors;

import java.util.HashMap;
import java.util.Map;

/**
 * a map of ARTD_B about brand,sex,taxon
 * 
 * @author shangyao
 * @date 2017年11月9日
 */
public class GetMap {
	public static Map<String, String> brandmap = new HashMap<String, String>() {

		private static final long serialVersionUID = 1L;

		{
			put("brand", "roc_band_code");
			put("Adidas", "adidas");
			put("Asics", "asics");
			put("Bearpaw", "bearpaw");
			put("Hunter", "hunter");
			put("Nike", "nike");
			put("Puma", "puma");
			put("The North Face", "the_north_face");
			put("Gary Vaynerchuk", "gary_vaynerchuk");
			put("I-Clip", "i_clip");
			put("Portenzo", "portenzo");
			put("Bulb Botz", "bulb_botz");
			put("Casio", "casio");
			put("Lego", "lego");
			put("Ace And Archer", "ace_and_archer");
			put("Anne Klein", "anne_klein");
			put("Christian Siriano", "christian_siriano");
			put("Dickies", "dickies");
			put("Dkny", "dkny");
			put("Fjallraven", "fjallraven");
			put("Fossil", "fossil");
			put("Furla", "furla");
			put("Herschel Supply Co", "herschel_supply_co_");
			put("Ivanka Trump", "ivanka_trump");
			put("Jansport", "jansport");
			put("Kate Spade", "kate_spade");
			put("Kipling", "kipling");
			put("Longchamp", "longchamp");
			put("Marc By Marc Jacobs", "marc_by_marc_jacobs");
			put("Michael Kors", "michael_kors");
			put("Montblanc", "montblanc");
			put("Nine West", "nine_west");
			put("Rebecca Minkoff", "rebecca_minkoff");
			put("Sandpiper Of California", "sandpiper_of_california");
			put("Swiss Gear", "swiss_gear");
			put("Tory Burch", "tory_burch");
			put("Vince Camuto", "vince_camuto");
			put("Wenger", "wenger");
			put("Chanel", "chanel");
			put("Dr.Jart+", "dr_jart_");
			put("Etude House", "etude_house");
			put("Innisfree", "innisfree");
			put("Laura Mercier", "laura_mercier");
			put("Makeup Eraser", "makeup_eraser");
			put("The Balm", "the_balm");
			put("Tonymoly", "tonymoly");
			put("Alex And Ani", "alex_and_ani");
			put("Christian Bernard", "christian_bernard");
			put("Exotic Identity", "exotic_ldentity");
			put("Invicta", "invicta");
			put("Lux Allure", "lux_allure");
			put("Rotary", "rotary");
			put("Tumi", "tumi");
			put("361.00", "361.00");
			put("Adam Tucker", "adam_tucker");
			put("Aerosoles", "aerosoles");
			put("Ahnu", "ahnu");
			put("Alfani", "alfani");
			put("Altra", "altra");
			put("American Rag", "american_rag");
			put("Amimoc", "amimoc");
			put("Anna", "anna");
			put("Ariat", "ariat");
			put("Avia", "avia");
			put("Bandolino", "bandolino");
			put("Bar Iii", "bar_lii");
			put("Bare Traps", "bare_traps");
			put("Bcbg", "bcbg");
			put("Bcbgeneration", "bcbgeneration");
			put("Bcbgmaxazria", "bcbg_max_azria");
			put("Bed Stu", "bed_stu");
			put("Bella Vita", "bella_vita");
			put("Betsey Johnson", "betsey_johnson");
			put("Birkenstock", "birkenstock");
			put("Blowfish", "blowfish");
			put("Blue By Betsey Johnson", "betsey_johnson");
			put("Bogs", "bogs");
			put("Born", "born");
			put("Breckelle", "breckelles");
			put("Breckelle'S", "breckelles");
			put("Calvin Klein", "calvin_klein");
			put("Calvin Klein Jeans", "calvin_klein");
			put("Caparros", "caparros");
			put("Carlos By Carlos Santana", "carlos_by_carlos_santana");
			put("Cat", "cat");
			put("Celeste", "celeste");
			put("Charles By Charles David", "charles_by_charles_david");
			put("Chinese Laundry", "chinese_laundry");
			put("Circa Joan & David", "circa_joan_david");
			put("Clarks", "clarks");
			put("Cliffs By White Mountain", "cliffs_by_white_mountai");
			put("Coach", "coach");
			put("Cole Haan", "cole_haan");
			put("Condor", "condor");
			put("Converse", "converse");
			put("Corso Como", "corso_como");
			put("Cougar", "cougar");
			put("crocs", "crocs");
			put("Dan Post", "dan_post");
			put("David Tate", "david_tate");
			put("Dc", "dc_shoes");
			put("Diba True", "diba_true");
			put("Diesel", "diesel");
			put("Dingo", "dingo");
			put("Dolce By Mojo Moxy", "mojo_moxy");
			put("Donald J Pliner", "donald_j_pliner");
			put("Dr. Martens", "dr_martens");
			put("Dr. Scholl'S", "dr_scholl_s");
			put("Dvs", "dvs");
			put("Easy Spirit", "easyspirit");
			put("Easy Street", "easy_street");
			put("Elie Tahari", "elie_tahari");
			put("Emu", "emu");
			put("Envy", "envy");
			put("Fergalicious", "fergalicious");
			put("Fila", "fila");
			put("Florsheim", "florsheim");
			put("Franco Sarto", "franco_sarto");
			put("G.I.L.I.", "g_i_l_i_");
			put("Giani Bernini", "giani_bernini");
			put("Grasshoppers", "grasshoppers");
			put("Guess", "guess");
			put("Gunmetal", "gunmetal");
			put("H By Halston", "h_by_halston");
			put("Havaianas", "havaianas");
			put("Heelys", "heelys");
			put("Hi-Tec", "hi_tec");
			put("Hoka One One", "hoka");
			put("Huf", "huf");
			put("Hush Puppies", "hush_puppies");
			put("Inc", "inc");
			put("Isaac Mizrahi Live", "isaac_mizrahi");
			put("J.D. Fisk", "j_d_fisk");
			put("Jack Rogers", "jack_rogers");
			put("Jessica Simpson", "jessica_simpson");
			put("Joe'S", "joe_s");
			put("Joie", "jjoie");
			put("Joules", "jjoules");
			put("Judith Ripka", "judith_ripka");
			put("Kamik", "kamik");
			put("Karen Scott", "karen_scott");
			put("Katy Perry", "katy_perry");
			put("Keds", "keds");
			put("Kelsi Dagger", "kelsidagger");
			put("Kenneth Cole", "kenneth_cole");
			put("Kenneth Cole Reaction", "kenneth_cole_reaction");
			put("Kensie", "kensie");
			put("K-Swiss", "k_swiss");
			put("Lamo", "lamo");
			put("Laredo", "laredo");
			put("Laura Britt", "laura_britt");
			put("Lauren Ralph Lauren", "ralph_lauren");
			put("Lifestride", "lifestride");
			put("Liliana", "liliana");
			put("Liz Claiborne", "liz_claiborne");
			put("Lori Goldstein", "lori_goldstein");
			put("Louise Et Cie", "louise_et_cie");
			put("Lucky", "lucky");
			put("Lucky Brand", "lucky_brand");
			put("Luxury Rebel", "luxury_rebel");
			put("Madison Harding", "madison_harding");
			put("Marc Fisher", "marc_fisher");
			put("Material Girl", "material_girl");
			put("Melissa", "melissa_shoes");
			put("Minnetonka", "minnetonka");
			put("Mizuno", "mizuno");
			put("Mountain Sole", "mountain_sole");
			put("Naturalizer", "naturalizer");
			put("New Balance", "newbalance");
			put("Newton Running", "newton_running");
			put("Nina", "nina");
			put("Onitsuka Tiger", "onitsuka_tiger");
			put("Palladium", "palladium");
			put("Polo Ralph Lauren", "polo_ralph_lauren");
			put("Propet", "propet");
			put("Rampage", "rampage");
			put("Red Circle", "red_circle");
			put("Reebok", "reebok");
			put("Reef", "reef");
			put("Rocket Dog", "rocket_dog");
			put("Ryka", "ryka");
			put("Sam Edelman", "sam_edelman");
			put("Sanuk", "sanuk");
			put("Saucony", "saucony");
			put("Schutz", "schutz");
			put("Skechers", "skechers");
			put("Sole Society", "sole_society");
			put("Sorel", "sorel");
			put("Sperry", "sperry");
			put("Steve Madden", "steve_madden");
			put("Style &Amp; Co", "style_amp_co");
			put("Style And Co", "styleandco_");
			put("Supra", "supra");
			put("Teva", "teva");
			put("Thalia Sodi", "thalia_sodi");
			put("Timberland", "timberland");
			put("Tommy Hilfiger", "tommy_hilfiger");
			put("Toms", "toms");
			put("Totes", "totes");
			put("Tretorn", "tretorn");
			put("Tuscany By Easy Street", "tuscany_by_easy_street");
			put("Ugg", "ugg");
			put("Under Armour", "under_armour");
			put("Vaneli", "vaneli");
			put("Vans", "vans");
			put("Very Volatile", "very_volatile");
			put("Vogue", "vogue");
			put("Walking Cradles", "walking_cradles");
			put("Wanted", "wanted");
			put("White Mountain", "white_mountain");
			put("Wonder", "wonder");
			put("Xoxo", "xoxo");
			put("Armani Exchange", "a|x_armani_exchange");
			put("Arnette", "arnette");
			put("Burberry", "burberry");
			put("Bvlgari", "bvlgari");
			put("Costa Del Mar", "costa_del_mar");
			put("Dolce & Gabbana", "dolce_gabbana");
			put("Electric", "electric");
			put("Emilio Pucci", "emilio_pucc");
			put("Emporio Armani", "emporio_armani");
			put("Fox", "fox");
			put("Giorgio Armani", "giorgio_armani");
			put("Gucci", "gucci");
			put("Kapten And Son", "kapten_and_son");
			put("Miu Miu", "miumiu");
			put("Oakley", "oakley");
			put("Persol", "persol");
			put("Polo", "polo");
			put("Prada", "prada");
			put("Quay", "quay");
			put("Ralph Lauren", "ralph_lauren");
			put("Ray-Ban", "rayban");
			put("Revo", "revo");
			put("Spy", "spy");
			put("Tiffany & Co", "tiffany");
			put("Tifosi", "tifosi");
			put("Tods", "tods");
			put("Tom Ford", "tom_ford");
			put("Versace", "versace");
			put("88 Rue Du Rhone", "88_rue_du_rhone");
			put("Avengers", "avengers");
			put("Ballast", "ballast");
			put("Black Dice", "black_dice");
			put("Braun", "braun");
			put("Bulova", "bulova");
			put("Chaps", "chaps");
			put("Citizen", "citizen");
			put("Cluse", "cluse");
			put("Disney", "disney");
			put("Disney Princess", "disney_princess");
			put("Dufonte", "dufonte");
			put("Esprit", "esprit");
			put("Esq", "esq");
			put("Ever After High", "ever_after_high");
			put("Festina", "festina");
			put("Frozen", "frozen");
			put("Gametime", "game_time");
			put("Geneva Platinum", "geneva_platinum");
			put("Guess Collection", "guess_collection");
			put("Hugo Boss", "hugo_boss");
			put("Ingersoll", "ingersoll");
			put("Inside Out", "inside_out");
			put("Joshua And Sons", "joshua_and_sons");
			put("Komono", "komono");
			put("Lacoste", "lacoste");
			put("Luminox", "luminox");
			put("Mango", "mango");
			put("Marc Jacobs", "marc_jacobs");
			put("Marvel Comics", "marvel_comics");
			put("Maserati", "maserati");
			put("Michele", "michele");
			put("Misfit", "Misfit");
			put("Movado", "movado");
			put("Mulco", "mulco");
			put("Muppets", "muppets");
			put("Nautica", "nautica");
			put("Nixon", "nixon");
			put("Orient", "orient");
			put("Oxbow", "oxbow");
			put("Peanuts", "peanuts");
			put("Polar", "polar");
			put("Precimax", "precimax");
			put("Pulsar", "pulsar");
			put("Rado", "rado");
			put("Raymond Weil", "raymond_weil");
			put("Seiko", "seiko");
			put("Skagen", "skagen");
			put("Star Wars", "star_wars");
			put("Suunto", "suunto");
			put("Swatch", "swatch");
			put("Swiss Military Hanowa", "swiss_military_hanowa");
			put("Swiss Precimax", "precimax");
			put("Szanto", "szanto");
			put("Tag Heuer", "tag_heuer");
			put("Ted Baker", "ted_baker");
			put("Thomas Earnshaw", "thomas_earnshaw");
			put("Timex", "timex");
			put("Tissot", "tissot");
			put("Ultimate Spider-Man", "ultimate_spider_man");
			put("Vestal", "vestal");
			put("Victorinox Swiss Army", "victorinox");
			put("Wittnauer", "wittnauer");
		}
	};
	public static Map<String, String> sexmap = new HashMap<String, String>() {

		private static final long serialVersionUID = 1L;

		{
			put("size", "roc_gender_code");
			put("Men's", "male");
			put("Women's", "female");
			put("Unisex", "neutral");
			put("Kid's Unisex", "kids");
			put("Boy's", "boy");
			put("Girl's", "girl");
			put("Children's", "kids");
			put("Fashion Trend: Ankle-High Suede Pump", "female");
			put("Fashion Trend: Ankle-High Suede Boot", "female");
			put("Fashion Trend: Knee-High Leather Boot", "female");
			put("Fashion Trend: Ankle-High Cotton Flat Shoe", "female");
			put("Fashion Trend: Ankle-High Canvas Flat Shoe", "female");
			put("Fashion Trend: Ankle-High Fabric Flat Shoe", "female");
			put("Tortoiseshell / Grey Color", "neutral");
			put("Green / Black Color", "neutral");
			put("Quartz Movement", "neutral");
			put("Quartz Movement", "neutral");
			put("Japanese Quartz Movement", "neutral");
			put("Swiss Parts Quartz Movement", "neutral");
		}
	};
	public static Map<String, String> taxonmap = new HashMap<String, String>() {

		private static final long serialVersionUID = 1L;

		{
			put("category", "roc_taxon_code");
			put("Apparel", "apparel_other");
			put("Books", "books");
			put("Cell Phones and Accessories", "electronics");
			put("Clocks", "clocks");
			put("Computers and Accessories", "electronics");
			put("Handbags", "functional_bags_other");
			put("Health and Beauty", "personal_care _makeup_other");
			put("Home Goods", "home_goods_other");
			put("Jewelry", "charaters");
			put("Luggage", "carry_ons");
			put("Office Products", "office_products_other");
			put("Shoes", "shoes_other");
			put("Sunglasses", "fashion_sunglasses");
			put("Watches", "feshion_watches");
		}
	};

}
